### ISSUE TITLE
对比方法是否能提供？

### ISSUE THREAD

**Issue by ghost** [xiaoyuan1996/labview2018-tutorial#1]
很不错的工作，代码复现的比较圆满。想问一下对比的方法是否能提供进这个项目内呢？  111

**Comment by xiaoyuan1996** [comment]
请移步至各个方法的原生代码库内，将其模型代码放置过来，接口写好就行。  
另轮子已经造好了，我们提供的数据您可以直接进行对比使用的。

**Comment by ghost** [comment]
好的谢谢
